{\rtf1\ansi\ansicpg1252\cocoartf2709
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 name: run main.py\
\
on:\
  schedule:\
    - cron: '0 0 * * 1' # At 00:00 on Monday\
\
jobs:\
  build:\
    runs-on: ubuntu-latest\
    steps:\
\
      - name: checkout repo content\
        uses: actions/checkout@v2 # checkout the repository content to github runner\
\
      - name: setup python\
        uses: actions/setup-python@v4\
        with:\
          python-version: '3.9' # install the python version needed\
          \
      - name: install python packages\
        run: |\
          python -m pip install --upgrade pip\
          pip install -r requirements.txt\
          \
      - name: execute py script # run main.py\
        env:\
          SOME_SECRET: $\{\{ secrets.SOME_SECRET \}\}\
        run: python main.py\
          \
      - name: commit files\
        run: |\
          git config --local user.email "action@github.com"\
          git config --local user.name "GitHub Action"\
          git add -A\
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)\
          \
      - name: push changes\
        uses: ad-m/github-push-action@v0.6.0\
        with:\
          github_token: $\{\{ secrets.GITHUB_TOKEN \}\}\
          branch: main }